# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 

# UI configs
title: "Photography by Thierry Kimenyi"
subtitle: "The places I am traveling to and The stories I am being told!"
author: ""Thierry Kimenyi"
bio: "I am a software developer who is also learnig photography"
publicise: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
social_urls:
  instagram: "https://www.instagram.com/thielypics"
  github: "https://www.github.com/tkimenyi"
  
